# Generated by Django 4.0.2 on 2022-02-16 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_rename_user_user_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_data',
            old_name='confirm_password',
            new_name='password2',
        ),
    ]
