# Generated by Django 4.0.2 on 2022-02-16 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_rename_confirm_password_user_data_password2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_data',
            name='password2',
        ),
    ]
