# Generated by Django 4.0.2 on 2022-02-16 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_remove_user_data_password2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_data',
            old_name='date_of_birth',
            new_name='DOB',
        ),
    ]
