# Generated by Django 4.0.2 on 2022-02-16 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_rename_date_of_birth_user_data_dob'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_data',
            old_name='DOB',
            new_name='date_of_birth',
        ),
    ]
