# Generated by Django 4.0.2 on 2022-02-17 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_user_data_confirm_password_user_data_profile_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_data',
            name='confirm_password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='profile_photo',
            field=models.ImageField(upload_to='profile'),
        ),
    ]
