# Generated by Django 4.0.2 on 2022-02-17 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_alter_user_data_confirm_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_data',
            name='profile_photo',
        ),
    ]
