# Generated by Django 4.0.2 on 2022-02-17 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0013_remove_user_data_profile_photo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_data',
            new_name='Userdata',
        ),
    ]
